{
  "dataset": "diving48",
  "num_classes": 48, 
  "num_queries": 5,
  "attribute_set_size": 25,
  "max_length": 128,
  "downsample": 2,
  "root": "../diving48/",
  "save_folder": "../exps",
  "tbx_folder": "../tbx",
  "pretrained_weights_path": "../S3D_K400.pth.tar"
}
