{
  "dataset": "diving48",
  "num_classes": 48, 
  "num_queries": 5,
  "attribute_set_size": 25,
  "max_length": 100000000,
  "K": 10,
  "downsample": 2,
  "root": "../diving48/",
  "save_folder": "../exps",
  "tbx_folder": "../tbx",
  "feature_file": "../features/diving48_all_features.pkl",
  "pretrained_weights_path": ""
}
