{
  "dataset": "gym288",
  "num_classes": 288, 
  "num_queries": 13,
  "attribute_set_size": 98,
  "max_length": 100000000,
  "K": 6,
  "downsample": 1,
  "root": "../FineGym/",
  "save_folder": "../exps",
  "tbx_folder": "../tbx",
  "feature_file": "../features/gym288_all_features.pkl",
  "pretrained_weights_path": ""
}
