{
  "dataset": "gym288",
  "num_classes": 288, 
  "num_queries": 13,
  "attribute_set_size": 98,
  "max_length": 48,
  "downsample": 1,
  "root": "../FineGym/",
  "save_folder": "../exps",
  "tbx_folder": "../tbx",
  "pretrained_weights_path": "../S3D_K400.pth.tar"
}
