{
  "dataset": "gym99",
  "num_classes": 99, 
  "num_queries": 12,
  "attribute_set_size": 66,
  "max_length": 48,
  "downsample": 1,
  "root": "../FineGym/",
  "save_folder": "../exps",
  "tbx_folder": "../tbx",
  "pretrained_weights_path": "../S3D_K400.pth.tar"
}
