{
  "dataset": "gym99",
  "num_classes": 99, 
  "num_queries": 12,
  "attribute_set_size": 66,
  "max_length": 100000000,
  "K": 6,
  "downsample": 1,
  "root": "../FineGym/",
  "save_folder": "../exps",
  "tbx_folder": "../tbx",
  "feature_file": "../features/gym99_all_features.pkl",
  "pretrained_weights_path": ""
}
